In [24]:
#### Import required packages
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sqlite3 as lite
sns.set(style="white")

In [60]:
#### Get information in the 13 tables
con = lite.connect('ThirteenDatasets.db')
rows_set1 = con.execute("Select x, y FROM Set01")
rows_set2 = con.execute("Select x, y FROM Set02")
rows_set3 = con.execute("Select x, y FROM Set03")
rows_set4 = con.execute("Select x, y FROM Set04")
rows_set5 = con.execute("Select x, y FROM Set05")
rows_set6 = con.execute("Select x, y FROM Set06")
rows_set7 = con.execute("Select x, y FROM Set07")
rows_set8 = con.execute("Select x, y FROM Set08")
rows_set9 = con.execute("Select x, y FROM Set09")
rows_set10 = con.execute("Select x, y FROM Set10")
rows_set11 = con.execute("Select x, y FROM Set11")
rows_set12 = con.execute("Select x, y FROM Set12")
rows_set13 = con.execute("Select x, y FROM Set13")

rows_t = [rows_set1, rows_set2, rows_set3, rows_set4, rows_set5, rows_set6, rows_set7, rows_set8, rows_set9, rows_set10,
         rows_set11, rows_set12, rows_set13,]

In [56]:
#### Save data, quicker way??
data_1 = {'x':0, 'y':0}
data_2 = {'x':0, 'y':0}
data_3 = {'x':0, 'y':0}
data_4 = {'x':0, 'y':0}
data_5 = {'x':0, 'y':0}
data_6 = {'x':0, 'y':0}
data_7 = {'x':0, 'y':0}
data_8 = {'x':0, 'y':0}
data_9 = {'x':0, 'y':0}
data_10 = {'x':0, 'y':0}
data_11 = {'x':0, 'y':0}
data_12 = {'x':0, 'y':0}
data_13 = {'x':0, 'y':0}

dict = {'data_1': data_1, 'data_2': data_2, 'data_3': data_3, 'data_4': data_4, 'data_5': data_5, 'data_6': data_6, 
       'data_7': data_7, 'data_8': data_8, 'data_9': data_9, 'data_10': data_10, 'data_11': data_11, 
       'data_12': data_12, 'data_13': data_13,}

for books in dict:
    arrayx=[]
    arrayy=[]

    for row in rows_set01:
        arrayx.append(row[0])
        arrayy.append(row[1])
data_1['x'] = arrayx
data_1['y'] = arrayy

arrayx=[]
arrayy=[]
for row in rows_set02:
    arrayx.append(row[0])
    arrayy.append(row[1])
data_2['x'] = arrayx
data_2['y'] = arrayy

In [58]:
data_1['x']

[32.3311102266,
 53.4214628807,
 63.92020226,
 70.2895057187,
 34.1188302357,
 67.6707164012,
 53.2591294055,
 63.5149808671,
 67.9805388133,
 67.3724659005,
 15.5607495229,
 71.7907676942,
 70.2425464362,
 64.9374355444,
 62.2135245453,
 67.2694004772,
 40.5701970446,
 74.7411813341,
 71.7683189223,
 76.1669198143,
 65.6236574431,
 50.8506336394,
 33.0240700249,
 39.7063261674,
 45.5964849542,
 42.9680469104,
 52.4944067819,
 46.0822757831,
 74.2477082092,
 64.5682641863,
 74.0216939058,
 62.3911805626,
 74.189036683,
 28.2367819396,
 75.7719387944,
 75.8552294691,
 65.9708570175,
 21.7780404779,
 67.7597962473,
 78.6171953363,
 68.5077081898,
 74.8850211598,
 66.4549036599,
 77.3178020985,
 58.9124603193,
 57.617447817,
 76.0882257967,
 57.4660505497,
 79.4283834934,
 76.3565221496,
 64.4050752632,
 40.6350418091,
 43.9498645857,
 30.9962205791,
 68.2307689907,
 72.0463894612,
 46.5927679682,
 49.2572183396,
 42.7817612539,
 65.475952195,
 71.9650826544,
 32.1464623358,
 31.8384976954,
 31.0052582572,
 80.4708943189,
 71.9641671122,
 78.0794214417,
 41.6775957748,
 65.953595185,
 62.9344593731,
 64.3737979844,
 72.5093283599,
 30.0522898741,
 28.0033242354,
 75.4012268619,
 38.9800154218,
 65.2199135479,
 73.0539899616,
 34.3983616372,
 43.4904501336,
 55.138737967,
 43.6843934333,
 35.9036097344,
 45.3780188805,
 39.7774828713,
 38.6644611569,
 39.0440366877,
 91.6399614428,
 47.4881326771,
 44.5902125769,
 39.0896145478,
 42.2293783752,
 37.0003871448,
 39.0520864793,
 37.4884147432,
 69.3595594592,
 43.542775926,
 39.8112302539,
 70.0689259404,
 70.0405435824,
 39.505789079,
 62.5168908529,
 72.1399254065,
 45.2515760666,
 42.0633045627,
 36.3556951539,
 30.3918276596,
 36.4490038543,
 40.467576002,
 81.7246168002,
 48.8231974964,
 35.6205617651,
 50.5839631148,
 61.8564651063,
 39.3237560262,
 42.1856791429,
 30.8469189898,
 29.3462004281,
 82.1105579783,
 38.3020058088,
 56.5841530218,
 33.3393742865,
 78.7742390407,
 27.9226442446,
 71.6978651182,
 74.1383313856,
 32.579020066,
 59.83218542,
 35.0306285457,
 74.3001198284,
 63.2501970628,
 34.1730737648,
 40.9138319319,
 62.8332930874,
 42.4767923803,
 52.0334562787,
 48.9070429644,
 59.8518383854,
 48.9604602016,
 46.8448551673,
 39.9630215796,
 66.704943997]

In [44]:
data_1
    
    

# Understand what the line below does! Try without the transpose and see the shape.
X = np.vstack((ug, gr, ri, iz, T)).T
M = np.vstack((ug, gr, ri, iz)).T




# Here I make a Pandas's DataFrame 
df = pd.DataFrame(X[0:1000, :], columns=['u-g', 'g-r', 'r-i', 'i-z', 'T'])
g = sns.PairGrid(df, diag_sharey=False)

# KDE plots are a form of smooth 2D histograms. This command ensures that the 
# panels below the diagonal all show the distributions as these smoothed 2D histograms using default
# settings (which might be a bad idea!)
g.map_lower(sns.kdeplot, cmap="Blues_d")

# This ensures that the panels above the diagonal shows the data relationships using a normal scatter plot.
g.map_upper(plt.scatter)

# Finally on the diagonal we could show a normal histogram - here I use a kernel density estimate of the 
# distribution which is a smoother version of the histogram.
g.map_diag(sns.kdeplot)

NameError: name 'data' is not defined